# Defines the services needed for the app, now using Firebase (no local DB service)
version: '3.8'

services:
  api:
    # Builds and runs the FastAPI service
    build: .
    ports:
      - "8001:8001"
    # Mount the service account key file into the container
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro # Mount as read-only
    environment:
      # Tell the Firebase Admin SDK where to find the credentials
      GOOGLE_APPLICATION_CREDENTIALS: /app/serviceAccountKey.json
      # Add any other environment variables your app might need
    # depends_on: # Removed dependency on local db service
    #  - db

# db: # Removed the PostgreSQL service definition
#   image: postgres:13
#   ...

# volumes: # Removed the pgdata volume definition
#  pgdata: