// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYGQD7olbFdM3opBh96cnHfuUTvgoC8Tw',
    appId: '1:79691429272:web:e163e6d7e7133c15aaa7ed',
    messagingSenderId: '79691429272',
    projectId: 'cs3354-group-project',
    authDomain: 'cs3354-group-project.firebaseapp.com',
    storageBucket: 'cs3354-group-project.firebasestorage.app',
    measurementId: 'G-WHT8PLXPMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsAa6QEa63dBEBfWQYw4k0EgdpYIIFRbE',
    appId: '1:79691429272:android:911e7bf53e531daeaaa7ed',
    messagingSenderId: '79691429272',
    projectId: 'cs3354-group-project',
    storageBucket: 'cs3354-group-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO0FC-KuSSDHiikt-taL1EMMn_CBSBpEk',
    appId: '1:79691429272:ios:b34caf431d38653caaa7ed',
    messagingSenderId: '79691429272',
    projectId: 'cs3354-group-project',
    storageBucket: 'cs3354-group-project.firebasestorage.app',
    iosBundleId: 'com.example.oneCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO0FC-KuSSDHiikt-taL1EMMn_CBSBpEk',
    appId: '1:79691429272:ios:b34caf431d38653caaa7ed',
    messagingSenderId: '79691429272',
    projectId: 'cs3354-group-project',
    storageBucket: 'cs3354-group-project.firebasestorage.app',
    iosBundleId: 'com.example.oneCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYGQD7olbFdM3opBh96cnHfuUTvgoC8Tw',
    appId: '1:79691429272:web:7ad006e5c06da5b9aaa7ed',
    messagingSenderId: '79691429272',
    projectId: 'cs3354-group-project',
    authDomain: 'cs3354-group-project.firebaseapp.com',
    storageBucket: 'cs3354-group-project.firebasestorage.app',
    measurementId: 'G-Q93LEK61DR',
  );

}